<?php

########################################################################
# Extension Manager/Repository config file for ext: "maps2"
#
# Auto generated by Extension Builder 2013-02-07
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Maps2',
	'description' => 'This extension gives you the possibility to make use of the Google Maps API',
	'category' => 'plugin',
	'author' => 'Stefan Froemken',
	'author_email' => 'sfroemken@jweiland.net',
	'author_company' => 'jweiland.net',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.2.0-6.2.99',
			'fluid' => '6.2.0-6.2.99',
			'typo3' => '6.2.0-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);