categories:
  Maps2:
    label: 'Maps2'
  Maps2.templates:
    label: 'Templates'
    parent: 'Maps2'
  Maps2.templates.infoWindowContent:
    label: 'Info Window Content'
    parent: 'Maps2.templates'
  Maps2.pages:
    label: 'Pages'
    parent: 'Maps2'

settings:
  maps2.templateRootPath:
    label: 'Templates'
    category: 'Maps2.templates'
    description: 'Path to template root'
    type: string
    default: 'EXT:maps2/Resources/Private/Templates/'
  maps2.partialRootPath:
    label: 'Partials'
    category: 'Maps2.templates'
    description: 'Path to partial root'
    type: string
    default: 'EXT:maps2/Resources/Private/Partials/'
  maps2.layoutRootPath:
    label: 'Layouts'
    category: 'Maps2.templates'
    description: 'Path to layout root'
    type: string
    default: 'EXT:maps2/Resources/Private/Layouts/'
  maps2.infoWindowContent.templatePath:
    label: 'Template path for info window content'
    category: 'Maps2.templates.infoWindowContent'
    description: 'If you click on a marker (POI) a little info window will appear. With this setting you can change the template to your own needs.'
    type: string
    default: 'EXT:maps2/Resources/Private/Templates/InfoWindowContent.html'
  maps2.infoWindowContent.imageHeight:
    label: 'Image Height'
    category: 'Maps2.templates.infoWindowContent'
    description: 'Define the image height for images in info window content of a POI. Values like 150c or 120m are also allowed.'
    type: string
    default: '150c'
  maps2.infoWindowContent.imageWidth:
    label: 'Image Width'
    category: 'Maps2.templates.infoWindowContent'
    description: 'Define the image width for images in info window content of a POI. Values like 150c or 120m are also allowed.'
    type: string
    default: '150c'

  maps2.storagePid:
    label: 'Default storage PID'
    category: 'Maps2.pages'
    description: 'Folder that stores all POIs'
    type: int
    default: 0
