services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JWeiland\Maps2\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  # Called by makeInstance in our RequestFactory
  JWeiland\Maps2\Client\Request\GoogleMaps\GeocodeRequest:
    public: true

  # Called by makeInstance in our RequestFactory
  JWeiland\Maps2\Client\Request\OpenStreetMap\GeocodeRequest:
    public: true

  # Called by makeInstance in our ClientFactory
  JWeiland\Maps2\Client\GoogleMapsClient:
    public: true

  # Called by makeInstance in our ClientFactory
  JWeiland\Maps2\Client\OpenStreetMapClient:
    public: true

  # Called by makeInstance in TYPO3's AbstractConditionMatcher
  JWeiland\Maps2\ExpressionLanguage\AllowMapProviderRequestFunctionsProvider:
    public: true

  # Called by makeInstance in our PoiCollection
  JWeiland\Maps2\Helper\MapHelper:
    public: true

  # Called by makeInstance in our GetEnvironmentViewHelper
  JWeiland\Maps2\Helper\SettingsHelper:
    public: true

  # Called by makeInstance in TYPO3's DataHandler
  JWeiland\Maps2\Hook\CreateMaps2RecordHook:
    public: true

  # Called by makeInstance in PoiCollection model to add foreign records
  JWeiland\Maps2\Service\MapService:
    public: true

  querybuilder.tx_maps2_domain_model_poicollection:
    class: 'TYPO3\CMS\Core\Database\Query\QueryBuilder'
    factory:
      - '@TYPO3\CMS\Core\Database\ConnectionPool'
      - 'getQueryBuilderForTable'
    arguments:
      - 'tx_maps2_domain_model_poicollection'

  JWeiland\Maps2\Service\PoiCollectionService:
    arguments:
      $queryBuilder: '@querybuilder.tx_maps2_domain_model_poicollection'

  JWeiland\Maps2\Tca\Maps2Registry:
    tags:
      - name: event.listener
        method: 'addMaps2DatabaseSchemasToTablesDefinition'
        event: TYPO3\CMS\Core\Database\Event\AlterTableDefinitionStatementsEvent
