name: Tests

on:
  push:
  pull_request:

jobs:
  testing:
    name: Testing

    runs-on: ubuntu-latest

    strategy:
      # This prevents cancellation of matrix job runs, if one or more already failed
      # and let the remaining matrix jobs be executed anyway.
      fail-fast: false

      matrix:
        php:
          - '8.2'
          - '8.3'
          - '8.4'

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Lint PHP'
        run: Build/Scripts/runTests.sh -b podman -p ${{ matrix.php }} -s lint

      - name: 'Install testing system'
        run: Build/Scripts/runTests.sh -b podman -p ${{ matrix.php }} -s composerUpdate

      - name: 'Composer validate'
        run: Build/Scripts/runTests.sh -b podman -p ${{ matrix.php }} -s composerValidate

      - name: 'Composer normalize'
        run: Build/Scripts/runTests.sh -b podman -p ${{ matrix.php }} -s composerNormalize -n

      - name: 'CGL'
        if: ${{ matrix.php <= '8.3' }}
        run: Build/Scripts/runTests.sh -b podman -n -p ${{ matrix.php }} -s cgl

      - name: 'Execute unit tests'
        run: Build/Scripts/runTests.sh -b podman -p ${{ matrix.php }} -s unit

      - name: 'Execute functional tests'
        run: Build/Scripts/runTests.sh -b podman -p ${{ matrix.php }} -d mysql -s functional

      - name: 'Execute functional tests'
        run: Build/Scripts/runTests.sh -b podman -p ${{ matrix.php }} -d mariadb -s functional

      - name: 'Execute functional tests'
        run: Build/Scripts/runTests.sh -b podman -p ${{ matrix.php }} -d postgres -s functional
