name: Test maps2 against TYPO3 11

on: [pull_request]

jobs:
  CGL:
    name: Coding Style

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Composer
        run: Build/Scripts/runTests.sh -t 11 -p 8.1 -s composerUpdate

      - name: Lint PHP
        run: Build/Scripts/runTests.sh -t 11 -p 8.1 -s lint

      - name: Validate code against CGL
        run: Build/Scripts/runTests.sh -t 11 -p 8.1 -s cgl -n

  testing:
    name: PHP Unit and Functional Tests
    needs: CGL

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        php: [ '7.4', '8.0', '8.1' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Composer
        run: Build/Scripts/runTests.sh -t 11 -p 7.4 -s composerUpdate

      - name: Functional tests with mariadb
        run: Build/Scripts/runTests.sh -t 11 -p ${{ matrix.php }} -d mariadb -s functional

      - name: Functional tests with postgres
        run: Build/Scripts/runTests.sh -t 11 -p ${{ matrix.php }} -d postgres -s functional

      - name: Functional tests with sqlite
        run: Build/Scripts/runTests.sh -t 11 -p ${{ matrix.php }} -d sqlite -s functional
